package com.tienda.presentation_layer;

/**
 *
 * @author isai_
 */
public class Frame extends javax.swing.JFrame {
   
    private static volatile Frame instance;
    
    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    @SuppressWarnings("DoubleCheckedLocking")
    public static Frame getInstance() {
        if (instance == null) {
            synchronized (Frame.class) { // Sincronización para hilos
                if (instance == null) {
                    instance = new Frame();
                }
            }
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(850, 550));
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
