package com.tienda.presentation_layer;

import javax.swing.*;

/**
 *
 * @author isai_
 */
public class LoginPanel extends javax.swing.JPanel {

    private static volatile LoginPanel instance;

    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    @SuppressWarnings("DoubleCheckedLocking")
    public static LoginPanel getInstance() {
        if (instance == null) {
            synchronized (LoginPanel.class) { // Sincronización para hilos
                if (instance == null) {
                    instance = new LoginPanel();
                }
            }
        }
        return instance;
    }

    public JButton getBtnAceptar() {
        return btnAceptar;
    }

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public JLabel getLblRecuperar3() {
        return lblRecuperar3;
    }

    public JPasswordField getTxtContraseña() {
        return txtContraseña;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRecuperar3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JPasswordField();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setMinimumSize(new java.awt.Dimension(850, 550));
        setPreferredSize(new java.awt.Dimension(850, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecuperar3.setBackground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12)); // NOI18N
        lblRecuperar3.setForeground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperar3.setText("Tienda-version-1.1 -SNAPSHOT");
        add(lblRecuperar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 220, 40));

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Swis721 Cn BT", 1, 60)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REGISTRO DEL SISTEMA");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setOpaque(true);
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 90));

        jLabel5.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("USUARIO:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 120, 60));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("CONTRASEÑA:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 60));

        txtUsuario.setBackground(new java.awt.Color(0, 102, 102));
        txtUsuario.setFont(new java.awt.Font("Swis721 Ex BT", 0, 13)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(153, 255, 204));
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtUsuario.setName("txtUsuario"); // NOI18N
        add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 270, 60));

        txtContraseña.setBackground(new java.awt.Color(0, 102, 102));
        txtContraseña.setFont(new java.awt.Font("Swis721 Ex BT", 0, 10)); // NOI18N
        txtContraseña.setForeground(new java.awt.Color(153, 255, 204));
        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtContraseña.setName("tx¨Password"); // NOI18N
        add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 270, 60));

        btnAceptar.setBackground(new java.awt.Color(0, 102, 102));
        btnAceptar.setFont(new java.awt.Font("Swis721 BT", 1, 15)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(204, 255, 204));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.setName("btnAceptar"); // NOI18N
        add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 330, 58));

        btnSalir.setBackground(new java.awt.Color(0, 102, 102));
        btnSalir.setFont(new java.awt.Font("Swis721 BT", 1, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(204, 255, 204));
        btnSalir.setText("SALIR");
        btnSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setName("btnSalir"); // NOI18N
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 330, 58));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grupo.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, 160));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRecuperar3;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
