package com.tienda.presentation_layer;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author isai_
 */
public class MenuPrincipalPanel extends javax.swing.JPanel {

    private static volatile MenuPrincipalPanel instance;

    /**
     * Creates new form MenuPrincipalPanel
     */
    public MenuPrincipalPanel() {
        initComponents();
    }

    @SuppressWarnings("DoubleCheckedLocking")
    public static MenuPrincipalPanel getInstance() {
        if (instance == null) {
            synchronized (MenuPrincipalPanel.class) { // Sincronización para hilos
                if (instance == null) {
                    instance = new MenuPrincipalPanel();
                }
            }
        }
        return instance;
    }

    public JButton getBtnCerrarSesion() {
        return btnCerrarSesion;
    }

    public JButton getBtnProductos() {
        return btnProductos;
    }

    public JButton getBtnProveedores() {
        return btnProveedores;
    }

    public JButton getBtnTransacciones() {
        return btnTransacciones;
    }

    public JButton getBtnUsuarios() {
        return btnUsuarios;
    }
    
    public JLabel getLblTitle() {
        return lblTitle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransacciones = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnProveedores = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnProductos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblRecuperar3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransacciones.setBackground(new java.awt.Color(0, 0, 0));
        btnTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sistema-de-gestion-de-contenidos.png"))); // NOI18N
        btnTransacciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btnTransacciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnTransacciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 250, 140));

        lblTitle.setBackground(new java.awt.Color(0, 204, 204));
        lblTitle.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Has iniciado sesión como:");
        lblTitle.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblTitle.setOpaque(true);
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 810, 40));

        btnProveedores.setBackground(new java.awt.Color(0, 0, 0));
        btnProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/proveedor.png"))); // NOI18N
        btnProveedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btnProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 250, 140));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PROVEEDORES");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 167, 25));

        btnProductos.setBackground(new java.awt.Color(0, 0, 0));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paquete.png"))); // NOI18N
        btnProductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btnProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 250, 140));

        jLabel6.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("PRODUCTOS");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 25));

        btnCerrarSesion.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha.png"))); // NOI18N
        btnCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 250, 140));

        jLabel2.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TRANSACCIONES");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 167, 30));

        jLabel10.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("CERRAR SESIÓN");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 167, 30));

        btnUsuarios.setBackground(new java.awt.Color(0, 0, 0));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profesionales.png"))); // NOI18N
        btnUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 250, 140));

        jLabel11.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("USUARIOS");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 167, 30));

        lblRecuperar3.setBackground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12)); // NOI18N
        lblRecuperar3.setForeground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperar3.setText("Tienda-version-1.1 -SNAPSHOT");
        add(lblRecuperar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, 220, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnTransacciones;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblRecuperar3;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
