package com.tienda.presentation_layer;

import javax.swing.*;

/**
 *
 * @author isai_
 */
public class ProveedorFrame extends javax.swing.JFrame {

    private static volatile ProveedorFrame instance;

    /**
     * Creates new form crearContra
     */
    private ProveedorFrame() {
        initComponents();
    }

    public static ProveedorFrame getInstance() {
        if (instance == null) {
            synchronized (ProveedorFrame.class) { // Sincronización para hilos
                if (instance == null) {
                    instance = new ProveedorFrame();
                }
            }
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmOptions = new javax.swing.JPopupMenu();
        miEliminar = new javax.swing.JMenuItem();
        container = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbProveedores = new javax.swing.JTable();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtRuc = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        miEliminar.setText("jMenuItem1");
        jpmOptions.add(miEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Proveedores");
        setResizable(false);

        container.setBackground(new java.awt.Color(153, 255, 204));
        container.setPreferredSize(new java.awt.Dimension(850, 550));
        container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Swis721 Lt BT", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(153, 255, 153));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setPreferredSize(new java.awt.Dimension(850, 550));
        container.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 130, 60));

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Swis721 Lt BT", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(153, 255, 153));
        btnRegresar.setText("REGRESAR");
        container.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 130, 60));

        jtbProveedores.setFont(new java.awt.Font("Swis721 Cn BT", 0, 13)); // NOI18N
        jtbProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbProveedores);

        container.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 1190, 330));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Swis721 Lt BT", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(153, 255, 153));
        btnLimpiar.setText("LIMPIAR");
        container.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 130, 60));

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("Swis721 Lt BT", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(153, 255, 153));
        btnModificar.setText("MODIFICAR");
        container.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 130, 60));

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Swis721 Ex BT", 0, 11)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(204, 204, 204));
        btnRefresh.setText("Refrescar tabla");
        container.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 680, 160, -1));
        container.add(txtRuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 390, 50));
        container.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 1250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }


    public JTable getJtbProveedores() {
        return jtbProveedores;
    }

    public JMenuItem getMiEliminar() {
        return miEliminar;
    }

    public JPopupMenu getJpmOptions() {
        return jpmOptions;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel container;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPopupMenu jpmOptions;
    private javax.swing.JTable jtbProveedores;
    private javax.swing.JMenuItem miEliminar;
    private javax.swing.JTextField txtRuc;
    // End of variables declaration//GEN-END:variables
}
