package com.tienda.presentation_layer;

import javax.swing.*;

/**
 *
 * @author isai_
 */
public class UsersPanel extends javax.swing.JPanel {

    private static volatile UsersPanel instance;

    /**
     * Creates new form UsersPanel
     */
    public UsersPanel() {
        initComponents();
    }

    @SuppressWarnings("DoubleCheckedLocking")
    public static UsersPanel getInstance() {
        if (instance == null) {
            synchronized (UsersPanel.class) { // Sincronización para hilos
                if (instance == null) {
                    instance = new UsersPanel();
                }
            }
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmOptions = new javax.swing.JPopupMenu();
        miEliminar = new javax.swing.JMenuItem();
        miDesconectar = new javax.swing.JMenuItem();
        txtUser = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        btnRegresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsuarios = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        btnRevelar = new javax.swing.JToggleButton();
        btnRefresh = new javax.swing.JButton();
        lblRecuperar3 = new javax.swing.JLabel();

        miEliminar.setText("jMenuItem1");
        jpmOptions.add(miEliminar);

        miDesconectar.setText("jMenuItem1");
        jpmOptions.add(miDesconectar);

        setBackground(new java.awt.Color(153, 255, 204));
        setPreferredSize(new java.awt.Dimension(850, 730));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 280, 60));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(153, 255, 153));
        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.setPreferredSize(new java.awt.Dimension(850, 550));
        add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 130, 60));

        txtPassword.setFont(new java.awt.Font("Swis721 Cn BT", 0, 12)); // NOI18N
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 240, 60));

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(153, 255, 153));
        btnRegresar.setText("REGRESAR");
        add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 130, 60));

        jtbUsuarios.setFont(new java.awt.Font("Swis721 Cn BT", 0, 13)); // NOI18N
        jtbUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtbUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 790, 400));

        jLabel6.setFont(new java.awt.Font("Swis721 BT", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nombre Completo:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 60));

        jLabel7.setFont(new java.awt.Font("Swis721 BT", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Password:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 110, 60));

        txtNombreCompleto.setFont(new java.awt.Font("Swis721 Cn BT", 0, 14)); // NOI18N
        add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 570, 60));

        jLabel8.setFont(new java.awt.Font("Swis721 BT", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Username:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, 60));

        btnLimpiar.setBackground(new java.awt.Color(0, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(153, 255, 153));
        btnLimpiar.setText("LIMPIAR");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 130, 60));

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("Swis721 BT", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(153, 255, 153));
        btnModificar.setText("MODIFICAR");
        add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 130, 60));

        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 570, 20));

        btnRevelar.setFont(new java.awt.Font("Swis721 Ex BT", 0, 12)); // NOI18N
        btnRevelar.setPreferredSize(new java.awt.Dimension(26, 11));
        add(btnRevelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 40, 40));

        btnRefresh.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh.setFont(new java.awt.Font("Swis721 BT", 0, 11)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(204, 204, 204));
        btnRefresh.setText("Refrescar tabla");
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(659, 680, 160, -1));

        lblRecuperar3.setBackground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setFont(new java.awt.Font("BankGothic Lt BT", 1, 12)); // NOI18N
        lblRecuperar3.setForeground(new java.awt.Color(0, 0, 0));
        lblRecuperar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRecuperar3.setText("Tienda-version-1.1 -SNAPSHOT");
        add(lblRecuperar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 220, 40));
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnRegistrar() {
        return btnRegistrar;
    }

    public JPasswordField getTxtPassword() {
        return txtPassword;
    }

    public JTextField getTxtNombreCompleto() {
        return txtNombreCompleto;
    }

    public JTextField getTxtUser() {
        return txtUser;
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JTable getJtbUsuarios() {
        return jtbUsuarios;
    }

    public JMenuItem getMiEliminar() {
        return miEliminar;
    }

    public JPopupMenu getJpmOptions() {
        return jpmOptions;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public JLabel getLblPassword() {
        return lblPassword;
    }

    public JToggleButton getBtnRevelar() {
        return btnRevelar;
    }

    public JMenuItem getMiDesconectar() {
        return miDesconectar;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JToggleButton btnRevelar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu jpmOptions;
    private javax.swing.JTable jtbUsuarios;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRecuperar3;
    private javax.swing.JMenuItem miDesconectar;
    private javax.swing.JMenuItem miEliminar;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
