package Capa_de_presentacion;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author isai_
 */
public class FrmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form crearContra
     */
    public FrmUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 280, 60));

        btnCrear.setText("CREAR");
        btnCrear.setPreferredSize(new java.awt.Dimension(850, 550));
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 220, 50));
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnCrear() {
        return btnCrear;
    }

    public JTextField getContra() {
        return txt;
    }

    public JTextField getUser() {
        return user;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
